trigger:
  branches:
    include:
      - main
  paths:
    include:
      - iac/**
      - ci-cd/terraform/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'terraform' # Make sure this matches the exact name of your variable group!
  - name: snykServiceConnection
    value: 'Synk' # Replace with actual connection name

stages:
- stage: ScanIaC
  displayName: Infrastructure Security Scan
  jobs:
  - job: SnykIaCScan
    displayName: Snyk IaC Scan
    steps:
    - checkout: self
    - task: SnykSecurityScan@1
      displayName: Run Snyk IaC Vulnerability Scan
      inputs:
        serviceConnectionEndpoint: $(snykServiceConnection)
        testType: 'iac'
        targetFile: 'iac/terraform/main.tf'
        monitorWhen: 'always'
        failOnIssues: true # Strict mode
        severityThreshold: 'high'

- stage: TerraformPlan
  displayName: Terraform Plan
  dependsOn: ScanIaC
  jobs:
  - job: Plan
    displayName: Terraform Plan
    steps:
    - checkout: self
    - script: |
        terraform init \
          -backend-config="address=$(TF_STATE_URL)" \
          -backend-config="update_method=PUT"
        terraform plan -out=tfplan
      workingDirectory: 'iac/terraform'
      displayName: 'Run Terraform Plan'
      env:
        TF_VAR_tenancy_ocid: $(TF_VAR_tenancy_ocid)
        TF_VAR_user_ocid: $(TF_VAR_user_ocid)
        TF_VAR_fingerprint: $(TF_VAR_fingerprint)
        TF_VAR_private_key: $(TF_VAR_private_key)
        TF_VAR_region: $(TF_VAR_region)
        TF_VAR_compartment_id: $(TF_VAR_compartment_id)
        TF_VAR_availability_domain: $(TF_VAR_availability_domain)
    - publish: 'iac/terraform/tfplan'
      artifact: tfplan

- stage: TerraformApply
  displayName: Terraform Apply
  dependsOn: TerraformPlan
  # Requires setting up an "Environment" named 'production' in Azure DevOps to enforce manual approval
  jobs:
  - deployment: Apply
    displayName: Terraform Apply
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - download: current
            artifact: tfplan
          - script: |
              cp $(Pipeline.Workspace)/tfplan/tfplan ./
              terraform init \
                -backend-config="address=$(TF_STATE_URL)" \
                -backend-config="update_method=PUT"
              terraform apply -auto-approve tfplan
            workingDirectory: 'iac/terraform'
            displayName: 'Run Terraform Apply'
            env:
              TF_VAR_tenancy_ocid: $(TF_VAR_tenancy_ocid)
              TF_VAR_user_ocid: $(TF_VAR_user_ocid)
              TF_VAR_fingerprint: $(TF_VAR_fingerprint)
              TF_VAR_private_key: $(TF_VAR_private_key)
              TF_VAR_region: $(TF_VAR_region)
              TF_VAR_compartment_id: $(TF_VAR_compartment_id)
              TF_VAR_availability_domain: $(TF_VAR_availability_domain)
