apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-tools
        image: alpine:3.18
        command: [sh, -c]
        args:
          - wget -qO- https://github.com/argoproj-labs/rollout-extension/releases/download/v0.4.0/extension.tar | tar -xf - -C /custom-tools
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
      containers:
      - name: argocd-server
        volumeMounts:
        - mountPath: /shared/app/custom
          name: custom-tools
