apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: codexrelic-api
  labels:
    app: codexrelic-api
spec:
  selector:
    matchLabels:
      app: codexrelic-api
  strategy:
    blueGreen:
      activeService: codexrelic-api-service
      previewService: codexrelic-api-preview-service
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        app: codexrelic-api
    spec:
      containers:
      - name: codexrelic-api
        image: DOCKER_IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "150m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
        - secretRef:
            name: codexrelic-secrets
