apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codexrelic.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "codexrelic.name" . }}
    helm.sh/chart: {{ include "codexrelic.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "codexrelic.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "codexrelic.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: MONGO_URI
              value: {{ .Values.env.MONGO_URI | quote }}
            - name: ADMIN_USER
              value: {{ .Values.env.ADMIN_USER | quote }}
            - name: ADMIN_PASS
              value: {{ .Values.env.ADMIN_PASS | quote }}
            - name: ADMIN_CODE
              value: {{ .Values.env.ADMIN_CODE | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
