trigger: none # Do not trigger on code push, only trigger via the Pipeline resource below

resources:
  pipelines:
  - pipeline: BuildPipeline
    source: '\Build\Code Build Pipelines' # Matching the exact folder and name from Azure DevOps
    trigger: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'aazammohammad193/codexrelic-api'
  # The Build Pipeline tags the image with its Run ID. We capture that here to deploy the exact same image.
  imageTag: '$(resources.pipeline.BuildPipeline.runID)'

stages:
- template: templates/deploy-stage.yml
  parameters:
    stageName: 'DeployToUAT'
    displayName: 'Deploy to UAT'
    environmentName: 'UAT'
    keyVaultName: 'kv-uat-codexrelic'
    namespace: 'uat'
    ingressDomain: 'uat.codexrelic.com'
    deployFolder: '/home/ubuntu/codexrelic-deploy/uat'
    maxReplicas: '2'

- template: templates/deploy-stage.yml
  parameters:
    stageName: 'DeployToStage'
    displayName: 'Deploy to Stage'
    environmentName: 'Stage'
    dependsOn: 'DeployToUAT'
    keyVaultName: 'kv-stage-codexrelic'
    namespace: 'stage'
    ingressDomain: 'stage.codexrelic.com'
    deployFolder: '/home/ubuntu/codexrelic-deploy/stage'
    maxReplicas: '2'

- template: templates/deploy-stage.yml
  parameters:
    stageName: 'DeployToProd'
    displayName: 'Deploy to Production'
    environmentName: 'Prod'
    dependsOn: 'DeployToStage'
    keyVaultName: 'kv-prod-codexrelic'
    namespace: 'prod'
    ingressDomain: 'codexrelic.com'
    deployFolder: '/home/ubuntu/codexrelic-deploy/prod'
    maxReplicas: '5'
