apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codexrelic-api-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mohdazam193/codexrelic.com.git'
    targetRevision: HEAD
    path: kubernetes/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
